# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build WinArk

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64

# WDK has been contained in the image according to https://github.com/actions/runner-images/issues/5235

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install WTL and WIL
      run: |
        .\vcpkg\vcpkg.exe install wil:x64-windows
        nuget install wtl -Version 10.0.10320

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install capstone[x86]:x86-windows-static
        .\vcpkg\vcpkg.exe install capstone[x86]:x64-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x86-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x64-windows-static

    - name: install Zydis kernel library
      run: |
        .\vcpkg\vcpkg.exe install zydis

    - name: Show tree
      run: |
        ls .
        tree .
        tree . | grep ".exe"

    - name: Compile WinArk
      run: |
        msbuild ./Anti-Rootkit.sln /p:Configuration=Release /p:Platform=x64
