# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build WinArk

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "**.md"
      - "**.png"
      - "License"
      - "/doc/**"
    types:
      - opened
      - synchronize
  workflow_dispatch:

env:
  # WDK for Windows 11, version 22H2
  WDK_URL: https://go.microsoft.com/fwlink/?linkid=2196230
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: ./Anti-Rootkit.sln
  
jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        BUILD_CONFIGURATION: [debug]
        PLATFORM: [x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'recursive'

    - name: Setup WDK version 22H2
      run: |
        $wdkSetupPath = "$Env:TEMP\wdksetup.exe"
        (New-Object Net.WebClient).DownloadFile('${{env.WDK_URL}}', $wdkSetupPath)
        Start-Process -FilePath $wdkSetupPath -ArgumentList "/quiet" -NoNewWindow -Wait 

    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v2
      with:
        msbuild-architecture: x64
  
# WDK has been contained in the image according to https://github.com/actions/runner-images/issues/5235

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat

    - name: Install WTL and WIL
      run: |
        .\vcpkg\vcpkg.exe install wil:x64-windows
        nuget install wtl -Version 10.0.10320

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg.exe install capstone[x86]:x86-windows-static
        .\vcpkg\vcpkg.exe install capstone[x86]:x64-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x86-windows-static
        .\vcpkg\vcpkg.exe install curlcpp:x64-windows-static

    - name: install Zydis kernel library
      run: |
        .\vcpkg\vcpkg.exe install zydis

    - name: Compile WinArk
      run: |
        msbuild /m /p:Configuration=${{matrix.BUILD_CONFIGURATION}} /p:Platform=${{matrix.PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
